version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: haritha
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  springboot-app:
    build: .
    container_name: springboot_app
    depends_on:
      - mysql
    ports:
      - "8001:8000" # Ensure this is correct
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: haritha
      SPRING_DATASOURCE_PASSWORD: rootpassword

  react-app:
    build: /home/haritha/Documents/GitHub/Haritha-JavaFSDTraining/docker/day1/fetchapi
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - springboot-app

volumes:
  mysql-data:
