name: Spring demo GHA

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if : github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -- file pom.xml

      - name: test
        run: mvn test
        if: ${{contains(github.event.head_commit.message,'test commit')}}

      - name: Upload jar to Github
        if: ${{success()}}
        uses: actions/upload-artifact@v3
        with:
          name: myapp-jar
          path: target/*.jar
