name: Spring demo GHA

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Job-level condition

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: Check result
        if: github.ref == 'refs/heads/main' && github.actor == 'haritha75'
        run: |
          echo "event = ${{ github.event_name }}"
          echo "Repository = ${{ github.repository }}"
          echo "user = ${{ github.actor }}"

      - name: Build with Maven
        run: mvn clean install -f pom.xml

      - name: Test
        run: mvn test
        if: ${{ contains(github.event.head_commit.message, 'test commit') }}

      - name: Upload jar to GitHub
        if: github.actor == 'haritha7' && success()
        uses: actions/upload-artifact@v3
        with:
            name: myapp-jar
            path: target/*.jar
